---
language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpstan analyse lib --level=7
  - ./vendor/bin/infection -min-msi=100
